import { IActions } from "../interfaces/interfaces";

const actions : IActions = {
    LLENAR_COORDENADAS: 'LLENAR_COORDENADAS',
    GET_EVENTS: 'GET_EVENTS',
    FILTRO_PRECIO: 'FILTRO_PRECIO',
    GET_ASISTENTES: 'GET_ASISTENTES',
    LOGIN: 'LOGIN_GOOGLE',
    GET_FAVORITES: "GET_FAVORITES",
    FILTRO_FAVORITOS: "FILTRO_FAVORITOS",
    LOGIN_NORMAL: "LOGIN_NORMAL",
    LOGOUT: 'LOGOUT',
    DELETE_FAVORITE_EVENT: "DELETE_FAVORITE_EVENT",

}

export default actions; 